### ISSUE TITLE
center video

### ISSUE THREAD

**Issue by icodeando** [rahulkarda/NASA-APOD#1]
Nice work!   I found a minor issue: videos are not centered
<img width="1324" alt="Screen Shot 2022-06-13 at 2 15 00 AM" src="https://user-images.githubusercontent.com/15069545/173291148-940a73b0-40d8-47a0-ba40-9ddd67ea1fe1.png">

**Comment by rahulkarda** [comment]
@devPatricia Thanks for noticing that! I've fixed the issue.
